grails-app/domain/com/coachingPortal/coaching/Batch.groovy
package com.coachingPortal.coaching

import com.coachingPortal.coaching.tasks.Timetable
import com.coachingPortal.practicePaper.PracticePaper
import com.coachingPortal.studyMaterial.StudyMaterial
import com.coachingPortal.users.Coaching

/**
 * Created by MAYANK DWIVEDI on 12/22/2015.
 */
class Batch {
    String name
    Date dateCreated
    Date lastUpdated

    static hasMany = [subscribeStudents:SubscribeUser,timetable:Timetable,practicePapers:PracticePaper,studyMaterials:StudyMaterial]
    static belongsTo = [coaching:Coaching]
    static constraints = {
        name nullable:false ,blank: false
        subscribeStudents nullable: true
        timetable nullable: true
        practicePapers nullable: true
        studyMaterials nullable: true
    }


}

grails-app/controllers/com/coachingPortal/backend/student/StudentBatchController.groovy
package com.coachingPortal.backend.student

import com.coachingPortal.coaching.Batch
import com.coachingPortal.coaching.SubscribeUser
import com.coachingPortal.users.Coaching
import com.coachingPortal.users.Person
import grails.plugins.springsecurity.Secured

@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_STUDENT'])
class StudentBatchController {
    def springSecurityService
    def index() {
        Coaching coaching=Coaching.findById(session.getAttribute('coachingId'))
        Person student=springSecurityService.currentUser as Person
        Set<Batch> subscribedBatches=new HashSet<Batch>()
        coaching.batches.each {batch->
            batch.subscribeStudents.each {subscribeStudent->
                if(subscribeStudent.student.id==student.id){
                    subscribedBatches.add(batch)
                }
            }
        }

       render(view: '/student/Batch/index',model: [batchList:subscribedBatches])
    }
}

grails-app/controllers/com/coachingPortal/backend/student/StudentHolidaysController.groovy
package com.coachingPortal.backend.student

import com.coachingPortal.coaching.tasks.Holidays
import com.coachingPortal.users.Coaching
import grails.plugins.springsecurity.Secured

@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_STUDENT'])
class StudentHolidaysController {

    def index() {

        Coaching coaching=Coaching.findById((session.getAttribute('coachingId')))
        render(view:'/student/Holidays/index' ,model:[holidaysInstanceCount: (Holidays.findAllByCoaching(coaching)).size(), holidaysInstanceList:Holidays.findAllByCoaching(coaching).sort{it.dateOfHoliday}])

    }
}

grails-app/controllers/com/coachingPortal/backend/student/StudentInfocenterController.groovy
package com.coachingPortal.backend.student

import com.coachingPortal.coaching.SubscribeUser
import com.coachingPortal.coaching.tasks.Infocenter
import com.coachingPortal.users.Coaching
import com.coachingPortal.users.Person
import grails.plugins.springsecurity.Secured

/**
 * Created by MAYANK DWIVEDI on 07-Apr-16.
 */
@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_STUDENT'])
class StudentInfocenterController {

    def springSecurityService

    def index(Long coachingId) {

        if(coachingId){
        Coaching coaching= Coaching.findById(coachingId)
        Person student=springSecurityService.currentUser as Person
            boolean isSubscribed=false
        Set<SubscribeUser> subscribeUsers=coaching.batches.subscribeStudents

        subscribeUsers.each {subscribeUser->

            if((subscribeUser.student.id.getAt(0)).equals(student.id)){
                isSubscribed=true
            }

        }


        if(isSubscribed==true){
            session.setAttribute('coachingId',coachingId)
            render(view:'/student/Infocenter/index' ,model:[infocenterInstanceCount: (Infocenter.findAllByCoaching(coaching)).size(), infocenterInstanceList:Infocenter.findAllByCoaching(coaching).sort{it.lastUpdated}])
        }else{
            flash.danger='Student is not subscribed to coaching.'
            redirect(controller:'studentProfile',action: 'home' )
        }

        }else{
            Coaching coaching=Coaching.findById(session.getAttribute('coachingId'))
            render(view:'/student/Infocenter/index' ,model:[infocenterInstanceCount: (Infocenter.findAllByCoaching(coaching)).size(), infocenterInstanceList:Infocenter.findAllByCoaching(coaching).sort{it.lastUpdated}])

        }
    }


    def show(Infocenter infocenterInstance) {
        render(view:'/student/Infocenter/show',model: [infocenterInstance:infocenterInstance])
    }
}

grails-app/controllers/com/coachingPortal/backend/student/StudentPracticePaperController.groovy
package com.coachingPortal.backend.student

import com.coachingPortal.coaching.Batch
import com.coachingPortal.practicePaper.PracticePaper
import com.coachingPortal.question.Question
import com.coachingPortal.result.Result
import com.coachingPortal.users.Person
import com.enums.Enums
import com.google.gson.Gson
import grails.converters.JSON
import grails.plugins.springsecurity.Secured

import java.util.concurrent.TimeUnit


@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_STUDENT'])
class StudentPracticePaperController {
    def springSecurityService

    def index = {
        Batch batch
        boolean isStudentSubscribed=false
        Person student=springSecurityService.currentUser as Person
        if(params.batchId){
            batch=Batch.findById(params.batchId)
            batch.subscribeStudents.each{subscribeStudent->
                if(subscribeStudent.student.id==student.id){
                    isStudentSubscribed=true
                }
            }
            if(isStudentSubscribed){
                session.setAttribute('batchId',params.batchId)
            }

        }else{
            isStudentSubscribed=true
            batch=Batch.findById(Long.parseLong((String)(session.getAttribute('batchId'))))
        }


        //List<PracticePaper> practicePaperList = PracticePaper.findAllByPracticePaperStatusAndCreatedBy(Enums.PracticePaperStatus.PUBLISH,student.subscribeUsers.coaching)
        Set<PracticePaper> practicePaperList = batch.practicePapers
        Map<PracticePaper,String> practicePaperStatusMap=new HashMap<PracticePaper,String>()
        practicePaperList.each{practicePaper->
            if(practicePaper.practicePaperStatus==Enums.PracticePaperStatus.PUBLISH){
            if(Result.findByPracticePaperAndStudent(practicePaper,student)){
                practicePaperStatusMap.put(practicePaper,'Attempted')
            }else{
                practicePaperStatusMap.put(practicePaper,'UnAttempted')
            }
           }
        }


        render(view: '/student/practicePaper/index', model: [practicePaperList: practicePaperList,practicePaperStatusMap:practicePaperStatusMap])
    }


    def instruction = {
        Person student=springSecurityService.currentUser as Person
        PracticePaper practicePaper = PracticePaper.findById(params.practicePaperId)
        Batch batch=Batch.findById(Long.parseLong((String)(session.getAttribute('batchId'))))
        Set<PracticePaper> practicePaperSet=batch.practicePapers
        if(practicePaperSet.contains(practicePaper)){

            if(Result.findByPracticePaperAndStudent(practicePaper,student)){
                flash.message='You have already given the test'
                redirect(controller: 'studentPracticePaper',action: 'index')
             }else{
                render(view: '/student/practicePaper/instruction', model: [practicePaper: practicePaper])
            }
        }else {
            flash.message='You are not allowed to take the test.'
            redirect(controller: 'studentPracticePaper',action: 'index')
        }
    }

    def test = {
        String timeLeft = null
        PracticePaper practicePaper = PracticePaper.findById(params.practicePaperId)
        if (session['endDate']) {
            Date presentDate = new Date()
            Date endDate = (Date) session['endDate']
            println("Start date is ---------" + presentDate + "and end date is --------" + endDate)

            // Get msec from each, and subtract.

            long duration = endDate.getTime() - presentDate.getTime();

            long diffInSeconds = TimeUnit.MILLISECONDS.toSeconds(duration) % 60;
            long diffInMinutes = TimeUnit.MILLISECONDS.toMinutes(duration);

            timeLeft = diffInMinutes + ':' + diffInSeconds
        } else {
            Date startDate = new Date()
            long startTime = startDate.getTime();
            Date endDate = new Date(startTime + (practicePaper.totalTime * 60000));
            session['endDate'] = endDate
            timeLeft = practicePaper.totalTime + ':' + '0'

        }
        ArrayList<String> subjectTypeList = new ArrayList<String>()
        practicePaper.practicePaperSubjects.each { examSubject ->
            subjectTypeList.add(examSubject.subjectType)
        }


        println("Sorted list is ---------------" + subjectTypeList)

        ArrayList<Question> questionArrayList = new ArrayList<Question>()
        Map<String, String> questionAnswerMap = new HashMap<String, String>()
        Map<String, String> questionStatusMap = new HashMap<String, String>()
        if (!session['questionAnswerMap']) {


            for (int i = 0; i < subjectTypeList.size(); i++) {
                ArrayList<Question> subjectTypeQuestionArrayList = new ArrayList<Question>()


                practicePaper.practicePaperSubjects.getAt(i).practicePaperQuestions.eachWithIndex { examQuestion, index ->

                    subjectTypeQuestionArrayList.add(examQuestion.question)
                    questionAnswerMap.put(examQuestion.question.uniqueId, '')
                    questionStatusMap.put(examQuestion.question.uniqueId, '')
                }
                if (i == 0) {
                    questionArrayList = subjectTypeQuestionArrayList
                }
                session[practicePaper.practicePaperSubjects.getAt(i).subjectType] = subjectTypeQuestionArrayList

            }
            session['questionAnswerMap'] = questionAnswerMap
            session['questionStatusMap'] = questionStatusMap
        } else {

            questionArrayList = session[subjectTypeList.get(0)]
            questionAnswerMap = session['questionAnswerMap']
            questionStatusMap = session['questionStatusMap']
        }

        Gson gsonInstance = new Gson();



        render(view: '/student/practicePaper/test', model: [practicePaper: practicePaper, timeLeft: timeLeft, subjectTypeList: subjectTypeList, question: questionArrayList.get(0), questionList: questionArrayList, subjectTypeJsonList: gsonInstance.toJson(subjectTypeList), markedAnswer: questionAnswerMap.get(questionArrayList.get(0).uniqueId), questionStatusMap: questionStatusMap])
    }

    def ax_getSelectedSubject = {
        def result = [:]
        if (params.subjectType) {

            ArrayList<Question> questionArrayList = session[params.subjectType]
            Map<String, String> questionAnswerMap = new HashMap<String, String>()
            Map<String, String> questionStatusMap = new HashMap<String, String>()
            questionStatusMap = session['questionStatusMap']
            questionAnswerMap = session['questionAnswerMap']
            questionAnswerMap.put(params.submittedQuestionUID, params.selectedAnswer)
            if (params.selectedAnswer == null) {
                questionStatusMap.put(params.submittedQuestionUID, 'passed')
            } else {
                questionStatusMap.put(params.submittedQuestionUID, 'answered')
            }


            session['questionAnswerMap'] = questionAnswerMap
            session['questionStatusMap'] = questionStatusMap
            Question nxtQuestion = questionArrayList.get(0)
            String markedAnswer = questionAnswerMap.get(nxtQuestion.uniqueId)

            result.subjectTypeQuestion = g.render(template: '/student/practicePaper/questionTemplate', model: [question: nxtQuestion, markedAnswer: markedAnswer])
            result.questionList = g.render(template: '/student/practicePaper/questionSerialNo', model: [questionList: questionArrayList, subjectType: params.subjectType, questionStatusMap: questionStatusMap])
            result.nxtOrPreQuestion = g.render(template: '/student/practicePaper/questionNxtPreTemplate', model: [subjectType: params.subjectType, questionNo: 1, questionListSize: questionArrayList.size()])
            result.result = 'SUCCESS'
            result.successMsg = 'Ajax call successful.'

        } else {
            result.errMsg = "Something went wrong. Please try again."
        }
        render result as JSON
    }

    def ax_getSelectedQuestion = {
        def result = [:]
        if (params.subjectType) {

            ArrayList<Question> questionArrayList = session[params.subjectType]
            Map<String, String> questionAnswerMap = new HashMap<String, String>()
            Map<String, String> questionStatusMap = new HashMap<String, String>()
            questionStatusMap = session['questionStatusMap']
            questionAnswerMap = session['questionAnswerMap']
            questionAnswerMap.put(params.submittedQuestionUID, params.selectedAnswer)
            /*if (params.markedReview == 'markedReview') {
                questionStatusMap.put(params.submittedQuestionUID, 'review')
            } else {*/
            if (params.selectedAnswer == null) {

                questionStatusMap.put(params.submittedQuestionUID, 'passed')
            } else {
                questionStatusMap.put(params.submittedQuestionUID, 'answered')
            }
            /*}*/
            session['questionAnswerMap'] = questionAnswerMap
            session['questionStatusMap'] = questionStatusMap
            Question nxtQuestion=null
            /*if(questionArrayList.size()==Integer.parseInt(params.questionNo)-1){
               nxtQuestion = questionArrayList.get(0)
            }else{*/
            nxtQuestion = questionArrayList.get(Integer.parseInt(params.questionNo) - 1)
            /*}*/

            String markedAnswer = questionAnswerMap.get(nxtQuestion.uniqueId)
            println("Question List size is " + questionArrayList.size())
            result.subjectTypeQuestion = g.render(template: '/student/practicePaper/questionTemplate', model: [question: nxtQuestion, markedAnswer: markedAnswer])

            result.nxtOrPreQuestion = g.render(template: '/student/practicePaper/questionNxtPreTemplate', model: [subjectType: params.subjectType, questionNo: Integer.parseInt(params.questionNo), questionListSize: questionArrayList.size()])

grails-app/controllers/com/coachingPortal/backend/student/StudentStudyMaterialController.groovy
package com.coachingPortal.backend.student

import com.coachingPortal.coaching.Batch
import com.coachingPortal.studyMaterial.StudyMaterial
import com.coachingPortal.users.Coaching
import com.coachingPortal.users.Person
import grails.plugins.springsecurity.Secured

/**
 * Created by MAYANK DWIVEDI on 11-Apr-16.
 */
@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_STUDENT'])
class StudentStudyMaterialController {
    def springSecurityService
    def index = {

        Batch batch
        boolean isStudentSubscribed=false
        if(params.batchId){
            batch=Batch.findById(params.batchId)
            Person student=springSecurityService.currentUser as Person

            batch.subscribeStudents.each{subscribeStudent->
                if(subscribeStudent.student.id==student.id){
                    isStudentSubscribed=true
                }
            }
            if(isStudentSubscribed){
                session.setAttribute('batchId',params.batchId)
            }

        }else{
            isStudentSubscribed=true
            batch=Batch.findById(Long.parseLong((String)(session.getAttribute('batchId'))))
        }


            if(isStudentSubscribed){
                List<StudyMaterial> studyMaterialList=StudyMaterial.findAllByBatch(batch)
                render(view: '/student/studyMaterial/list',model: [studyMaterialList:studyMaterialList])
            }else{
                flash.danger='Student is not subscribed to batch.'
                redirect(controller: 'studentBatch',action: 'index')
            }
      }


    def downloadFile = {

        StudyMaterial studyMaterial=StudyMaterial.findBySmUniqueId(params.smId)
        if(studyMaterial){
            String filePath=grailsApplication.config.studyMaterial.location.toString()+ '/'+studyMaterial.batch.coaching.id+'/'+studyMaterial.storedLocation
            File fileInstance = new File(filePath)
            if (fileInstance == null) {
                flash.message = "Document not found."
                redirect(action: 'list')
            } else {
                response.setContentType("APPLICATION/OCTET-STREAM")
                response.setHeader("Content-Disposition", "Attachment;Filename=\"${fileInstance.name}\"")
                def fileInputStream = new FileInputStream(fileInstance)
                def outputStream = response.getOutputStream()
                outputStream << fileInstance.bytes
                outputStream.flush()
                outputStream.close()
                fileInputStream.close()
            }
        }
    }

}

grails-app/views/student/Timetable/index.gsp
<%@ page import="com.coachingPortal.coaching.Batch" contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
    <meta name="layout" content="main" />
</head>

<body>
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <div class="well">
                <g:render template="/student/myCoaching/myBatchNavBar" model="[navBarSelectedItem:'TimeTable']"/>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
              <g:render template="/common/errorAndMessage" />
        </div>
    </div>

      <div class="row">
        <div class="col-lg-12">
            <div class="well">
                <h3>${(Batch.findById(Long.parseLong((String)(session.getAttribute('batchId'))))).name}->Timetable</h3>
                <hr>
                <g:if test="${batchInstance?.timetable.size()>0}">
                    <table class="table table-responsive table-hover">
                        <tr>
                            <th>#</th>
                            <th>Day</th>
                            <th>Start Time</th>
                            <th>Duration</th>
                            <th>Subject Name</th>
                            <th>Last Updated</th>

                        </tr>
                        <tbody>
                        <g:each in="${timetableList}" var="task" status="i">
                            <tr>
                                <td>${i + 1}</td>
                                <td>${task?.day}</td>
                                <td>${task?.startTime}</td>
                                <td>${task?.duration}</td>
                                <td>${task?.subjectName}</td>
                                <td><g:formatDate format="dd-MM-yyyy" date="${task?.lastUpdated}"/></td>
                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </g:if>
                <g:else>
                    <div class="alert alert-info">
                        <i class="fa fa-warning"></i> Time table not updated by coaching.
                    </div>
                </g:else>
            </div>
        </div>
    </div>

</div>
</body>
</html> 

grails-app/views/student/Timetable/show.gsp
<%@ page import="com.coachingPortal.coaching.tasks.Timetable" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'timetable.label', default: 'Timetable')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-timetable" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-timetable" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list timetable">
			
				<g:if test="${timetableInstance?.day}">
				<li class="fieldcontain">
					<span id="day-label" class="property-label"><g:message code="timetable.day.label" default="Day" /></span>
					
						<span class="property-value" aria-labelledby="day-label"><g:fieldValue bean="${timetableInstance}" field="day"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timetableInstance?.startTime}">
				<li class="fieldcontain">
					<span id="startTime-label" class="property-label"><g:message code="timetable.startTime.label" default="Start Time" /></span>
					
						<span class="property-value" aria-labelledby="startTime-label"><g:fieldValue bean="${timetableInstance}" field="startTime"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timetableInstance?.duration}">
				<li class="fieldcontain">
					<span id="duration-label" class="property-label"><g:message code="timetable.duration.label" default="Duration" /></span>
					
						<span class="property-value" aria-labelledby="duration-label"><g:fieldValue bean="${timetableInstance}" field="duration"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timetableInstance?.subjectName}">
				<li class="fieldcontain">
					<span id="subjectName-label" class="property-label"><g:message code="timetable.subjectName.label" default="Subject Name" /></span>
					
						<span class="property-value" aria-labelledby="subjectName-label"><g:fieldValue bean="${timetableInstance}" field="subjectName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timetableInstance?.batch}">
				<li class="fieldcontain">
					<span id="batch-label" class="property-label"><g:message code="timetable.batch.label" default="Batch" /></span>
					
						<span class="property-value" aria-labelledby="batch-label"><g:link controller="studentBatch" action="show" id="${timetableInstance?.batch?.id}">${timetableInstance?.batch?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:timetableInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${timetableInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>