grails-app/domain/com/coachingPortal/coaching/Batch.groovy
package com.coachingPortal.coaching

import com.coachingPortal.coaching.tasks.Timetable
import com.coachingPortal.practicePaper.PracticePaper
import com.coachingPortal.studyMaterial.StudyMaterial
import com.coachingPortal.users.Coaching

/**
 * Created by MAYANK DWIVEDI on 12/22/2015.
 */
class Batch {
    String name
    Date dateCreated
    Date lastUpdated

    static hasMany = [subscribeStudents:SubscribeUser,timetable:Timetable,practicePapers:PracticePaper,studyMaterials:StudyMaterial]
    static belongsTo = [coaching:Coaching]
    static constraints = {
        name nullable:false ,blank: false
        subscribeStudents nullable: true
        timetable nullable: true
        practicePapers nullable: true
        studyMaterials nullable: true
    }


}

grails-app/domain/com/coachingPortal/practicePaper/PracticePaper.groovy
package com.coachingPortal.practicePaper

import com.coachingPortal.users.Coaching
import com.enums.Enums

class PracticePaper {

    String examName
    Coaching createdBy
    String uniqueId = UUID.randomUUID().toString()
    Integer totalTime

    Integer examPrice
    String paymentType
    /*paid/unpaid*/
    String openStatus
    /*openStatus can be private,public ,both*/
    Integer totalQuestions
    Date dateCreated
    Date lastUpdated
    Enums.PracticePaperStatus practicePaperStatus = Enums.PracticePaperStatus.UNPUBLISH

    static hasMany = [practicePaperSubjects: PracticePaperSubject]

    static mapping = {
        practicePaperSubjects sort: 'subjectType', order: 'asc'
        paymentType sqlType: 'varchar(6)'
        openStatus sqlType: 'varchar(7)'
    }

    static constraints = {
        examName nullable: false, blank: false
        openStatus nullable: false, blank: false
        paymentType nullable: false, blank: false
        totalTime min: 1, nullable: false
        examPrice nullable: true
        totalQuestions nullable: true
        practicePaperSubjects nullable: true
        createdBy nullable: false,blank:false
    }


    def beforeInsert() {
        uniqueId = UUID.randomUUID().toString()
    }



    //Has error
    def totalSubjectsList() {
        List<PracticePaperSubject> practicePaperSubjectList = this.examSubjects
        String subjectsList = null
        for (int i = 0; i < practicePaperSubjectList.size(); i++) {
            if (i == 0) {
                subjectsList = subjectsList + practicePaperSubjectList.get(i)
            } else {
                subjectsList = subjectsList + ',' + practicePaperSubjectList.get(i)
            }
        }
        return subjectsList
    }


}

grails-app/domain/com/coachingPortal/practicePaper/PracticePaperQuestion.groovy
package com.coachingPortal.practicePaper

import com.coachingPortal.question.Question
import org.jsoup.Jsoup


class PracticePaperQuestion {

    Question question

    static belongsTo = [practicePaperSubject: PracticePaperSubject]

    static constraints = {
        question nullable: false
    }

    public String getQuestionShortText(){
        String quesStr = Jsoup.parse(this.question.questionText)
        if(quesStr.length()>70){
            return quesStr.subSequence(0,70)+"..."
        }else{
            return quesStr
        }
    }
}

grails-app/domain/com/coachingPortal/question/Question.groovy
package com.coachingPortal.question

import com.coachingPortal.users.Coaching
import com.enums.Enums

/**
 * Created by MAYANK DWIVEDI on 6/1/2015.
 */
class Question {

    String questionText
    Date dateCreated
    Date lastUpdated
    Coaching createdBy
    Enums.Difficulty difficulty = Enums.Difficulty.EASY
    String subjectType
    String uniqueId = UUID.randomUUID().toString()
    String option1
    String option2
    String option3
    String option4
    QuestionHeader questionHeader

    static hasMany = [images: QuestionImage]
    static hasOne = [answer: Answer]



    static constraints = {
        questionText blank: false, nullable: false
        createdBy blank: false, nullable: false
        difficulty blank: false, nullable: false
        subjectType blank: false, nullable: false
        option1 nullable: true
        option2 nullable: true
        option3 nullable: true
        option4 nullable: true
        answer unique: true
        questionHeader nullable: true
        images nullable: true
    }

    static mapping = {
        questionText type: 'text'
        option1 type: 'text'
        option2 type: 'text'
        option3 type: 'text'
        option4 type: 'text'
        questionHeader lazy: false
    }

    String toString(){
        return this.questionText
    }
}

grails-app/controllers/com/coachingPortal/backend/coaching/CoachingBatchController.groovy
package com.coachingPortal.backend.coaching

import com.coachingPortal.coaching.Batch
import com.coachingPortal.users.Coaching
import grails.plugins.springsecurity.Secured
import grails.transaction.Transactional

/**
 * Created by MAYANK DWIVEDI on 2/12/2016.
 */
@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_STUDENT', 'ROLE_COACHING'])
@Transactional(readOnly = true)
class CoachingBatchController {

    def springSecurityService

    def index = {
        Coaching coaching = springSecurityService.currentUser as Coaching
        Set<Batch> batchList = coaching.batches
        render(view: '/coaching/Batch/index', model: [batchList: batchList])
    }

    def create = {
        render(view: '/coaching/Batch/create')
    }

    @Transactional
    def save(Batch batchInstance) {
        Coaching coaching = springSecurityService.currentUser as Coaching
        coaching.addToBatches(batchInstance)

        if (batchInstance == null) {
            notFound()
            return
        }

        if (!batchInstance.validate()) {
            render(view: '/coaching/Batch/create', model: [batchInstance: batchInstance])
        } else {
            coaching.save(flush: true)
            flash.success = 'Batch created successfully'
            redirect(action: "index")
        }

    }
}

grails-app/controllers/com/coachingPortal/backend/coaching/CoachingController.groovy
package com.coachingPortal.backend.coaching

import com.coachingPortal.CoachingSignUpCO
import com.coachingPortal.security.Role
import com.coachingPortal.security.User
import com.coachingPortal.security.UserRole
import com.coachingPortal.users.Coaching
import grails.plugins.springsecurity.Secured

/**
 * Created by MAYANK DWIVEDI on 7/1/2015.
 */
@Secured(['ROLE_COACHING', 'ROLE_ADMIN','IS_AUTHENTICATED_FULLY'])
class CoachingController {

    def mandrillHelperService

   def addCoachingForm={
       render (view: '/coaching/profile/addCoachingForm')
   }

    def addCoaching={CoachingSignUpCO coachingSignUpCO->


        if (coachingSignUpCO.validate()) {

            Coaching coaching = new Coaching(coachingSignUpCO)
            coaching.enabled = true
            coaching.save(flush: true)

            UserRole.create(coaching, Role.findByAuthority("ROLE_COACHING"))

            Map<String, String> toAddressMap = [:]
            toAddressMap.put(coaching?.username, coaching?.name)
            String htmlTemplate = g.render(template: '/emailTemplates/coachingAdded', model: [person: coaching ])
            mandrillHelperService.sendMandrillMail(toAddressMap,'Added to PrepareEasy',htmlTemplate,'Team PrepareEasy',(coaching as User))
            //commonService.sendMandrillMail(toAddressMap, "Activate your account to get started with ClashMate", htmlTemplate, CommonMethod.MANDRILL_FROM_NAME)
            flash.success="Coaching account created successfully"
            redirect(controller: 'coachingProfile',action: 'home')

        } else {
            render(view: '/coaching/profile/addCoachingForm', model: [signUpCO: coachingSignUpCO])
        }

    }
}

grails-app/controllers/com/coachingPortal/backend/coaching/CoachingHolidaysController.groovy
package com.coachingPortal.backend.coaching

import com.coachingPortal.coaching.tasks.Holidays
import com.coachingPortal.users.Coaching
import grails.plugins.springsecurity.Secured
import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.NOT_FOUND
import static org.springframework.http.HttpStatus.OK

@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_STUDENT','ROLE_COACHING'])
@Transactional(readOnly = true)
class CoachingHolidaysController {

    def springSecurityService

    /*static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]*/

    def index(Integer max) {
        Coaching coaching=springSecurityService.currentUser as Coaching
        params.max = Math.min(max ?: 10, 100)
        render(view:'/coaching/Holidays/index' ,model:[holidaysInstanceCount: (Holidays.findAllByCoaching(coaching)).size(), holidaysInstanceList:Holidays.findAllByCoaching(coaching).sort{it.dateOfHoliday}])
    }

    def show(Holidays holidaysInstance) {
        render(view:'/coaching/Holidays/show',model: [holidaysInstance:holidaysInstance])
    }

    def create() {
        render(view:'/coaching/Holidays/create',model: [holidaysInstance:new Holidays(params)])
    }

    @Transactional
    def save() {
        Holidays holidaysInstance=new Holidays(params)
        Coaching coaching=springSecurityService.currentUser as Coaching
        coaching.addToHolidays(holidaysInstance)
        if (holidaysInstance == null) {
            redirect(controller: 'coachingHolidays',action:'index' )
            return
        }

        if (!holidaysInstance.validate()) {
            render(view: 'create',model: [holidaysInstance:holidaysInstance])
        }else {
            coaching.save(flush: true)
            flash.success='Holiday added successfully'
            redirect(controller: 'coachingHolidays',action:'index' )
        }

    }

    def edit(Holidays holidaysInstance) {
        render(view: '/coaching/Holidays/edit',model: [holidaysInstance:holidaysInstance])
    }

    @Transactional
    def update(Holidays holidaysInstance) {
        if (holidaysInstance == null) {
            redirect(controller: 'coachingInfocenter',action: 'index')
            return
        }

        if (holidaysInstance.hasErrors()) {
            render(view: '/coaching/Holidays/edit',model: [holidaysInstance:holidaysInstance])
            return
        }

        holidaysInstance.save(insert: false, update: true)

        flash.success='Holiday updated successfully'
        redirect(controller: 'coachingHolidays',action: 'index')
    }

    @Transactional
    def delete(Holidays holidaysInstance) {

        if (holidaysInstance == null) {
            notFound()
            return
        }

        holidaysInstance.delete(flush:true)
        flash.message='Holiday deleted successfully'
        redirect controller: 'coachingHolidays', action:"index", method:"GET"
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'holidays.label', default: 'Holidays'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/coachingPortal/backend/coaching/CoachingInfocenterController.groovy
package com.coachingPortal.backend.coaching

import com.coachingPortal.coaching.tasks.Infocenter
import com.coachingPortal.users.Coaching
import grails.plugins.springsecurity.Secured
import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.NOT_FOUND

@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_STUDENT','ROLE_COACHING'])
@Transactional(readOnly = true)
class CoachingInfocenterController {

    def springSecurityService
/*
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
*/

    def index(Integer max) {
        Coaching coaching=springSecurityService.currentUser as Coaching
        params.max = Math.min(max ?: 10, 100)
        render(view:'/coaching/Infocenter/index' ,model:[infocenterInstanceCount: (Infocenter.findAllByCoaching(coaching)).size(), infocenterInstanceList:Infocenter.findAllByCoaching(coaching).sort{it.lastUpdated}])

    }

    def show(Infocenter infocenterInstance) {
        render(view:'/coaching/Infocenter/show',model: [infocenterInstance:infocenterInstance])
    }

    def create() {
        render(view:'/coaching/Infocenter/create',model: [infocenterInstance:new Infocenter(params)])
    }

    @Transactional
    def save() {
        Infocenter infocenterInstance=new Infocenter(params)
        Coaching coaching=springSecurityService.currentUser as Coaching
        infocenterInstance.coaching=coaching
        coaching.addToInfocenter(infocenterInstance)

        if (infocenterInstance == null) {
            redirect(controller: 'coachingInfocenter',action: 'index')
            return
        }

        if (!infocenterInstance.validate()) {
            render(view: '/coaching/Infocenter/create',model: [infocenterInstance:infocenterInstance])
        }else {
            coaching.save flush: true
            flash.success='Information added successfully'
            redirect(controller: 'coachingInfocenter',action: 'index')
        }
    }

    def edit(Infocenter infocenterInstance) {
        render(view: '/coaching/Infocenter/edit',model: [infocenterInstance:infocenterInstance])
        }

    @Transactional
    def update(Infocenter infocenterInstance) {
        if (infocenterInstance == null) {
            redirect(controller: 'coachingInfocenter',action: 'index')
            return
        }

        if (infocenterInstance.hasErrors()) {
            render(view: '/coaching/Infocenter/edit',model: [infocenterInstance:infocenterInstance])
            return
        }

        infocenterInstance.save(insert: false, update: true)

        flash.success='Information updated successfully'
        redirect(controller: 'coachingInfocenter',action: 'index')
    }

    @Transactional
    def delete(Infocenter infocenterInstance) {

        if (infocenterInstance == null) {
            notFound()
            return
        }

        infocenterInstance.delete flush:true

        /*request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Infocenter.label', default: 'Infocenter'), infocenterInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }*/

        flash.success='Information deleted successfully'
        redirect controller: 'coachingInfocenter', action:"index", method:"GET"
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'infocenter.label', default: 'Infocenter'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/coachingPortal/backend/coaching/CoachingMailController.groovy
package com.coachingPortal.backend.coaching

import com.coachingPortal.ContactUsCO
import com.coachingPortal.security.User
import grails.plugins.springsecurity.Secured

/**
 * Created by MAYANK DWIVEDI on 6/18/2015.
 */
@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_ADMIN','ROLE_COACHING'])
class CoachingMailController {
    def mandrillHelperService
    def springSecurityService

    def index={
    render(view: '/coaching/communicate/home')
    }

    def sms={
        render(view: '/coaching/communicate/sms/smsForm')
    }

    def email={
        render(view: '/coaching/communicate/mail/mailForm')
    }

    def mailToUserForm(){
    render(view: '/coaching/communicate/mail/mailToUserForm',model: [mailId:params?.mailId])
    }

    def sendMailUser(){
        ContactUsCO contactUsCO=new ContactUsCO()
        Map<String,String> recipientMailId=new HashMap<String,String>()
        String mailIds=params.mailId
        String[] arrayMailId=mailIds.split(',')

        arrayMailId.each {arrayMailIdEach->
            recipientMailId.put(arrayMailIdEach,'Dummy')
        }

        contactUsCO.mailId=arrayMailId[0]
        contactUsCO.body=params.body
        contactUsCO.subject=params.subject
        if(contactUsCO.validate()){
            User mailSender=springSecurityService.currentUser as User

            String htmlTemplate = g.render(template: '/emailTemplates/mailTemplate', model: [message: params.body ])

            mandrillHelperService.sendMandrillMail(recipientMailId,params.subject,htmlTemplate,'Team PrepareEasy',mailSender)

            flash.success='Mail sent successfully'
            redirect(controller: 'subscribeStudent',action: 'index')
        }else{
            render(view:'/coaching/communicate/mail/mailToUserForm' ,model: [contactUsCO:contactUsCO,mailId:params.mailId]);
        }

    }

}

grails-app/controllers/com/coachingPortal/backend/coaching/CoachingResultController.groovy
package com.coachingPortal.backend.coaching

import com.coachingPortal.ApachePOI
import com.coachingPortal.practicePaper.PracticePaper
import com.coachingPortal.result.Result
import grails.plugins.springsecurity.Secured

import javax.servlet.http.HttpServletResponse

/**
 * Created by MAYANK DWIVEDI on 6/12/2015.
 */
@Secured(['IS_AUTHENTICATED_FULLY', 'ROLE_ADMIN', 'ROLE_COACHING'])
class CoachingResultController {

    def practicePaperResult = {

        PracticePaper practicePaper = PracticePaper.findById(params.practicePaperId)
        List<Result> resultList = Result.findAllByPracticePaper(practicePaper)
        HttpServletResponse response = response
        ApachePOI apachePOI = new ApachePOI()

        apachePOI.resultPracticePaperAdmin(response, resultList, practicePaper.examName)


    }
}

grails-app/views/coaching/practicePaper/_practiceSubjectQuestionsShort.gsp
<div class="panel panel-default">
    <div class="panel-heading">${practiceSubject}(${practiceSubject.numOfQuestion})
        <span class="pull-right"><a
                href="${createLink(controller: 'coachingPracticePaper', action: 'renderAddQuestionsToSubject', params: [practiceSubjectId:practiceSubject.id,practicePaperId: practicePaper.id])}">Add or Remove Questions</a>
        </span>
    </div>

    <div class="panel-body">
        <g:if test="${!practiceSubject?.practicePaperQuestions?.isEmpty()}">
            <table class="table table-responsive table-condensed">
                <tbody>
                <tr>
                    <th>#</th>
                    <th>Question</th>
                </tr>
                <g:each in="${practiceSubject?.practicePaperQuestions}" var="practiceQuestion" status="i">
                    <tr>
                        <td>${i + 1}</td>
                        <td>${raw(practiceQuestion?.questionShortText)}</td>
                    </tr>
                </g:each>
                </tbody>
            </table>
        </g:if>
        <g:else>
            <div class="alert alert-danger">
                No questions added yet.
            </div>
        </g:else>
    </div>
</div>

grails-app/views/coaching/practicePaper/addPracticePaperForm.gsp
<%@ page import="com.coachingPortal.subject.SubjectType" %>
<html>
<head>
    <title></title>
    <meta name="layout" content="main"/>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <script>
        jQuery(document).ready(function () {
            jQuery("#btnleft").click(function () {
                jQuery("#allsubjects option:selected").each(function () {
                    jQuery("#selectedsubjects").append(jQuery(this).clone());
                    jQuery(this).remove();
                });
            });

            jQuery("#btnright").click(function () {
                jQuery("#selectedsubjects option:selected").each(function () {
                    jQuery("#allsubjects").append(jQuery(this).clone());
                    jQuery(this).remove();
                });
            });
        });

        function validateForm() {

           var selectedSubjectValues = [];

            $('#selectedsubjects option').each(function() {
                selectedSubjectValues.push($(this).val());
            });

            if(selectedSubjectValues.length==0){
                alert('Please add atleast one subject')
                return false;
            }else{
                document.getElementById('selectedSubjectValuesId').value=selectedSubjectValues
                return true;
            }

        }

    </script>
</head>

<body>
<div class="container">

<g:render template="/common/errorAndMessage" model="[someInstance:practicePaper]"/>

    <div class="row">
        <div class="col-lg-12 well">
           <g:render template="/coaching/myCoaching/myBatchNavBar" model="[navBarSelectedItem:'PracticePaper']"/>
         </div>
    </div>


    <div class="row well well-lg">
        <div class="col-lg-12">
            <h3 >Add Practice Paper<a
                    href="${createLink(controller: 'coachingPracticePaper', action: 'index')}"
                    class="btn btn-primary pull-right">Back to Practice Papers</a></h3>
            <hr>

            <form action="${createLink(controller: 'coachingPracticePaper', action: 'addPracticePaper')}" method="post"
                  name="practicePaperForm">
                <input type="hidden" name="selectedSubjectValues" id="selectedSubjectValuesId" value="">
                <div class="form-group col-lg-9 ${hasErrors(bean: practicePaper, field: "examName", 'has-error')}">
                    <label for="examName">Exam Name</label>
                    <input type="text" class="form-control" name="examName" id="examName" placeholder="Enter exam name"
                           autofocus="autofocus" value="${practicePaper?.examName}" required="required">
%{--
                    <helper:renderFieldError bean="${practicePaper}" field="examName"/>
--}%
                </div>

                <div class="form-group col-lg-3 ${hasErrors(bean: practicePaper, field: "totalTime", 'has-error')}">
                    <label for="totalTime">Total Time (in minutes)</label>
                    <input type="text" class="form-control" name="totalTime" id="totalTime"
                           placeholder="Total time" autofocus="autofocus" value="${practicePaper?.totalTime}" required="required">
%{--
                    <helper:renderFieldError bean="${practicePaper}" field="totalTime"/>
--}%
                </div>

                <div class="form-group col-lg-6 col-lg-offset-3" >
                <div style="float: left;">
                    <g:select name="allsubjects" id="allsubjects" multiple="multiple" from="${SubjectType.list().sort { it.subject }}" style="width: 200px;height: 230px;"/>
                </div>
                    <div class="btn" style="float: left; padding-top: 20px;">
                        <br/>
                        <br/>
                        <br/>
                        <input id="btnleft" value=">>>>" type="button" />
                        <br/>
                        <br/>
                        <br/>
                        <input id="btnright" value="<<<<" type="button" />
                    </div>
                    <div style="float: left;">
                        <select name="selectedsubjects" id="selectedsubjects" multiple="multiple" style="width: 200px;height: 230px;">
                        </select>
                    </div>

                </div>


                <div class="form-group">
                       <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                        <button type="submit" class="btn btn-primary btn-block" value="Submit" onclick="return validateForm()">Submit</button>
                       </div>

                    <div class="col-xs-6 col-md-6 col-sm-6 col-lg-6">
                        <button type="reset" class="btn btn-default btn-block" value="Reset">Reset</button>
                    </div>
                </div>

            </form>

        </div>
    </div>
</div>

</body>
</html>

grails-app/views/coaching/practicePaper/index.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
    <meta name="layout" content="main"/>
</head>

<body>
<div class="container">
    <g:render template="/common/errorAndMessage"/>

    <div class="row">
        <div class="col-lg-12">
            <div class="well">
                <g:render template="/coaching/myCoaching/myBatchNavBar" model="[navBarSelectedItem:'PracticePaper']"/>
            </div>
        </div>
    </div>


    <div class="row well well-lg">
        <div class="col-lg-12">
            <h3 class="text-primary"><i class="fa fa-book"></i> Practice Papers<a href="${createLink(controller:'coachingPracticePaper',action: 'addPracticePaperForm' )}" class="btn btn-primary pull-right">Add Practice Paper</a></h3>
            <strong>Change the status of practice paper to 'UnPublish' to add or remove questions</strong>
            <hr>
            <g:if test="${!practicePaperList?.empty}">
                <table class="table table-responsive table-hover">
                    <tr>
                        <th>#</th>
                        <th>Exam Name</th>
                        <th>Total time</th>
                        <th>Date Created</th>
                        <th>Topics</th>
                        <th>Status</th>
                        <th>Result</th>
                    </tr>
                    <tbody>
                    <g:each in="${practicePaperList}" var="practicePaper" status="i">
                        <tr>
                            <td>${i + 1}</td>
                            <g:if test="${(practicePaper.practicePaperStatus).toString().equals('UnPublish')}">
                                <td><a href="${createLink(controller:'coachingPracticePaper',action: 'renderSubjects',params: [practicePaperId:practicePaper.id] )}">${practicePaper?.examName}</a> </td>
                            </g:if>
                            <g:else>
                                <td>${practicePaper?.examName} </td>
                            </g:else>
                            <td>${practicePaper?.totalTime}</td>
                            <td>${practicePaper?.dateCreated?.format("MMMM dd, yyyy")}</td>
                            <td>
                                <g:each in="${practicePaper?.practicePaperSubjects}" var="practiceSubjects">
                                    ${practiceSubjects}|
                                </g:each>
                            </td>
                            <td><a href="${createLink(controller:'coachingPracticePaper',action: 'changeStatus',params: [practicePaperId:practicePaper.id])}">${practicePaper?.practicePaperStatus}</a></td>
                            <td><a href="${createLink(controller:'coachingResult',action: 'practicePaperResult',params: [practicePaperId:practicePaper.id])}"><i class="fa fa-file-excel-o"></i></a></td>
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </g:if>
            <g:else>
                <div class="alert alert-info">
                    <i class="fa fa-warning"></i> There are no practice papers added till now.
                </div>
            </g:else>




        </div>
    </div>
</div>
</body>
</html>

grails-app/views/coaching/practicePaper/practiceSubjects.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
    <meta name="layout" content="main" />

</head>

<body>
<div class="space20"></div>
<div class="container">

    <div class="row">
        <div class="col-lg-12 well">
            <g:render template="/coaching/myCoaching/myBatchNavBar" model="[navBarSelectedItem:'PracticePaper']"/>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="well well-sm">
                <h3 class="dark_blue_text_color">Practice Paper - ${practicePaper.examName}<g:link controller="coachingPracticePaper" action="index" class="btn btn-primary pull-right">Back to Practice Papers</g:link> </h3>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
                <g:each in="${practicePaper.practicePaperSubjects}" var="practiceSubject">
                    <div class="col-lg-6">
                       <g:render template="/coaching/practicePaper/practiceSubjectQuestionsShort" model="[practiceSubject:practiceSubject,practicePaper:practicePaper]"/>
                    </div>
                </g:each>

        </div>
    </div>


</div>
</body>
</html>
    
	

grails-app/views/coaching/practicePaper/renderAddQuestionsToSubject.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>
    <meta name="layout" content="main"/>

</head>

<body>

<div class="container">

<g:render template="/common/errorAndMessage"/>

    <div class="row">
        <div class="col-lg-12 well">
            <g:render template="/coaching/myCoaching/myBatchNavBar" model="[navBarSelectedItem:'PracticePaper']"/>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="well well-sm">
                <h3 class="dark_blue_text_color">${practicePaper?.examName}-${practicePaperSubject?.subjectType}<a href="${createLink(controller:'coachingPracticePaper',action: 'renderSubjects',params: [practicePaperId:practicePaper.id] )}" class="btn  pull-right">Back to subjects</a></h3>
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="well well-sm">
                <g:if test="${!questionList?.isEmpty()}">
                    <table class="table table-responsive table-condensed">
                        <tbody>
                        <tr>
                            <th>#</th>
                            <th>Question</th>
                            <th>Action</th>
                        </tr>
                        <g:each in="${questionList}" var="question" status="i">
                            <tr>
                                <td>${i + 1}</td>
                                <td>${raw(question.questionText)}</td>
                                <td>
                                    <g:if test="${practicePaperUniqueIdList.contains(question.uniqueId)}">
                                        <a href="${createLink(controller: 'coachingPracticePaper', action: 'ax_addOrRemoveQuestion', params: [questionUniqueId: question.uniqueId, practicePaperSubjectId: practicePaperSubject.id,practicePaperId:practicePaper.id, questionAction: 'remove'])}"
                                           class="btn btn-sm btn-danger">Remove</a>
                                    </g:if>
                                    <g:else>
                                        <a href="${createLink(controller: 'coachingPracticePaper', action: 'ax_addOrRemoveQuestion', params: [questionUniqueId: question.uniqueId, practicePaperSubjectId: practicePaperSubject.id,practicePaperId:practicePaper.id, questionAction: 'add'])}"
                                           class="btn btn-sm btn-success">Add</a>
                                    </g:else>

                                </td>
                            </tr>
                        </g:each>
                        </tbody>
                    </table>
                </g:if>
                <g:else>
                    <div class="alert alert-danger">
                        No questions added by you.
                    </div>
                </g:else>
            </div>
        </div>
    </div>
</div>
</body>
</html>